services:
  - type: web
    name: transcriptor-backend
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt && python preinstall_models.py"
    startCommand: "python run.py"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
